name: Lint Markdown

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint Markdown
        run: git ls-files -z '*.md' | xargs -0r npx -y @lint-md/cli -c .lintmdrc -s
